export { default as Banner } from './banner.jpg';
export { default as bannerSignUp } from './bannerSignUp.jpg';
export { default as omSad } from './om-sad.png';
export { default as omHappy } from './om-happy.png';
export { default as Error404 } from './404.png';
export { default as ComingSoon } from './coming_soon.png';
export { default as SWWrong } from './sww.png';
export { default as Logo } from './logo.png';
export { default as User } from './user.png';
